/* ═══════════════════════════════════════════════════════════════
   Toolkit — sw.js  (Service Worker)
   Strategy:
     · HTML pages  → Network-first, cache fallback
     · Static assets (CSS/JS/fonts/images) → Cache-first, network fallback
   Update cycle: bump CACHE_VERSION to evict old caches on next visit.
═══════════════════════════════════════════════════════════════ */

'use strict';

const CACHE_VERSION = 'v27';
const CACHE_NAME    = `toolkit-${CACHE_VERSION}`;

/* Generated by build.py --offline. Keeping every tool shell and module here
   means the whole site works after the very first successful visit. */
const TOOL_PAGES = [
  // TOOL-PRECACHE:PAGES:START
  'tools/aes-gcm.html',
  'tools/ascii.html',
  'tools/aspect-ratio.html',
  'tools/base32.html',
  'tools/base64-to-image.html',
  'tools/base64.html',
  'tools/bcrypt.html',
  'tools/binary-text.html',
  'tools/bytes.html',
  'tools/case-converter.html',
  'tools/certificate-inspector.html',
  'tools/color-contrast.html',
  'tools/color-converter.html',
  'tools/color-palette.html',
  'tools/cron-assistant.html',
  'tools/csp-generator.html',
  'tools/css-clamp.html',
  'tools/css-minifier.html',
  'tools/css-specificity.html',
  'tools/csv-to-json.html',
  'tools/csv-viewer.html',
  'tools/curl-builder.html',
  'tools/date-duration.html',
  'tools/deduplicate-lines.html',
  'tools/fake-data.html',
  'tools/favicon-generator.html',
  'tools/file-checksum.html',
  'tools/find-replace.html',
  'tools/gradient.html',
  'tools/hash.html',
  'tools/hex-codec.html',
  'tools/hmac.html',
  'tools/html-codec.html',
  'tools/html-minifier.html',
  'tools/http-header-analyzer.html',
  'tools/http-status.html',
  'tools/image-compressor.html',
  'tools/image-dimensions.html',
  'tools/image-metadata.html',
  'tools/image-to-base64.html',
  'tools/js-minifier.html',
  'tools/json-diff.html',
  'tools/json-formatter.html',
  'tools/json-minifier.html',
  'tools/json-sorter.html',
  'tools/json-to-csv.html',
  'tools/json-to-markdown.html',
  'tools/json-to-typescript.html',
  'tools/json-to-yaml.html',
  'tools/json-validator.html',
  'tools/jwt-decoder.html',
  'tools/line-numbers.html',
  'tools/lorem-ipsum.html',
  'tools/markdown.html',
  'tools/meta-tags.html',
  'tools/mime-lookup.html',
  'tools/number-base.html',
  'tools/open-graph.html',
  'tools/password-strength.html',
  'tools/password.html',
  'tools/pem-jwk.html',
  'tools/percentage.html',
  'tools/qr-batch.html',
  'tools/qr-generator.html',
  'tools/qr-reader.html',
  'tools/query-string.html',
  'tools/random-color.html',
  'tools/random-name.html',
  'tools/random-number.html',
  'tools/random-string.html',
  'tools/random-token.html',
  'tools/regex-tester.html',
  'tools/robots-generator.html',
  'tools/rot13.html',
  'tools/rsa-keypair.html',
  'tools/sitemap-generator.html',
  'tools/slug.html',
  'tools/sql-formatter.html',
  'tools/svg-optimizer.html',
  'tools/temperature.html',
  'tools/text-cleaner.html',
  'tools/text-diff.html',
  'tools/text-reverser.html',
  'tools/text-sorter.html',
  'tools/time-zone-converter.html',
  'tools/timestamp.html',
  'tools/totp.html',
  'tools/unicode-inspector.html',
  'tools/unit-converter.html',
  'tools/unix-permissions.html',
  'tools/url-builder.html',
  'tools/url-codec.html',
  'tools/url-parser.html',
  'tools/user-agent.html',
  'tools/uuid-validator.html',
  'tools/uuid.html',
  'tools/word-counter.html',
  'tools/xml-formatter.html',
  'tools/xml-to-json.html',
  'tools/yaml-to-json.html',  // TOOL-PRECACHE:PAGES:END
];
const TOOL_SCRIPTS = [
  // TOOL-PRECACHE:SCRIPTS:START
  'assets/js/tools/ascii.js',
  'assets/js/tools/aspect-ratio.js',
  'assets/js/tools/base32.js',
  'assets/js/tools/base64-to-image.js',
  'assets/js/tools/base64.js',
  'assets/js/tools/bcrypt.js',
  'assets/js/tools/binary-text.js',
  'assets/js/tools/bytes.js',
  'assets/js/tools/case-converter.js',
  'assets/js/tools/color-converter.js',
  'assets/js/tools/color-palette.js',
  'assets/js/tools/css-minifier.js',
  'assets/js/tools/csv-to-json.js',
  'assets/js/tools/deduplicate-lines.js',
  'assets/js/tools/expansion-tools.js',
  'assets/js/tools/fake-data.js',
  'assets/js/tools/favicon-generator.js',
  'assets/js/tools/file-checksum.js',
  'assets/js/tools/find-replace.js',
  'assets/js/tools/gradient.js',
  'assets/js/tools/hash.js',
  'assets/js/tools/hex-codec.js',
  'assets/js/tools/hmac.js',
  'assets/js/tools/html-codec.js',
  'assets/js/tools/html-minifier.js',
  'assets/js/tools/http-status.js',
  'assets/js/tools/image-dimensions.js',
  'assets/js/tools/image-metadata.js',
  'assets/js/tools/image-to-base64.js',
  'assets/js/tools/js-minifier.js',
  'assets/js/tools/json-diff.js',
  'assets/js/tools/json-formatter.js',
  'assets/js/tools/json-minifier.js',
  'assets/js/tools/json-sorter.js',
  'assets/js/tools/json-to-csv.js',
  'assets/js/tools/json-to-yaml.js',
  'assets/js/tools/json-validator.js',
  'assets/js/tools/jwt-decoder.js',
  'assets/js/tools/line-numbers.js',
  'assets/js/tools/lorem-ipsum.js',
  'assets/js/tools/markdown.js',
  'assets/js/tools/meta-tags.js',
  'assets/js/tools/mime-lookup.js',
  'assets/js/tools/number-base.js',
  'assets/js/tools/open-graph.js',
  'assets/js/tools/password-strength.js',
  'assets/js/tools/password.js',
  'assets/js/tools/percentage.js',
  'assets/js/tools/qr-batch.js',
  'assets/js/tools/qr-generator.js',
  'assets/js/tools/qr-reader.js',
  'assets/js/tools/query-string.js',
  'assets/js/tools/random-color.js',
  'assets/js/tools/random-name.js',
  'assets/js/tools/random-number.js',
  'assets/js/tools/random-string.js',
  'assets/js/tools/random-token.js',
  'assets/js/tools/regex-tester.js',
  'assets/js/tools/robots-generator.js',
  'assets/js/tools/rot13.js',
  'assets/js/tools/slug.js',
  'assets/js/tools/sql-formatter.js',
  'assets/js/tools/svg-optimizer.js',
  'assets/js/tools/temperature.js',
  'assets/js/tools/text-cleaner.js',
  'assets/js/tools/text-diff.js',
  'assets/js/tools/text-reverser.js',
  'assets/js/tools/text-sorter.js',
  'assets/js/tools/timestamp.js',
  'assets/js/tools/unit-converter.js',
  'assets/js/tools/url-builder.js',
  'assets/js/tools/url-codec.js',
  'assets/js/tools/url-parser.js',
  'assets/js/tools/user-agent.js',
  'assets/js/tools/uuid-validator.js',
  'assets/js/tools/uuid.js',
  'assets/js/tools/word-counter.js',
  'assets/js/tools/xml-formatter.js',
  'assets/js/tools/yaml-to-json.js',  // TOOL-PRECACHE:SCRIPTS:END
];

/* Core assets to precache on install */
const PRECACHE_ASSETS = [
  'index.html',
  '404.html',
  'assets/css/core.css',
  'assets/css/components.css',
  'assets/css/compatibility.css',
  'assets/css/pages/home.css',
  'assets/css/pages/tool.css',
  'assets/css/features/expansion-tools.css',
  'assets/images/favicon.svg',
  'assets/images/favicon-192.svg',
  'assets/images/favicon-512.svg',
  'manifest.json',
  /* Core JS */
  'assets/js/core/utils.js',
  'assets/js/core/nav.js',
  'assets/js/core/i18n-expansion.js',
  'assets/js/core/i18n.js',
  'assets/js/core/tools-data.js',
  'assets/js/core/extra-tools-data.js',
  'assets/js/core/command-palette.js',
  'assets/js/pages/home.js',
  ...TOOL_PAGES,
  ...TOOL_SCRIPTS,
  /* Self-hosted fonts */
  'assets/fonts/SpaceGrotesk.ttf',
  'assets/fonts/JetBrainsMono.ttf',
  'assets/fonts/JetBrainsMono-Italic.ttf',
  /* Vendor libraries (QR tools) */
  'assets/js/vendor/qrcode.min.js',
  'assets/js/vendor/jsQR.min.js',
  'assets/js/vendor/qrious.min.js',
];

/* ─── Install ────────────────────────────────────────────────── */
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_ASSETS))
      .then(() => self.skipWaiting())
  );
});

/* ─── Activate ───────────────────────────────────────────────── */
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key !== CACHE_NAME)
            .map((key) => caches.delete(key))
        )
      )
      .then(() => self.clients.claim())
  );
});

/* ─── Fetch ──────────────────────────────────────────────────── */
self.addEventListener('fetch', (event) => {
  const { request } = event;

  /* Only handle GET requests */
  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  /* Skip non-http(s) schemes (chrome-extension etc.) */
  if (!url.protocol.startsWith('http')) return;

  /* Only handle same-origin requests (fonts are now local) */
  if (url.origin !== self.location.origin) return;

  const isHTML = request.headers.get('accept')?.includes('text/html');

  /* ── HTML → Network-first ── */
  if (isHTML) {
    event.respondWith(networkFirst(request));
    return;
  }

  /* ── All other same-origin assets → Cache-first ── */
  event.respondWith(cacheFirst(request));
});

/* ─── Strategies ─────────────────────────────────────────────── */

/**
 * Network-first: try the network, cache the response, fall back to cache.
 * Falls back to 404.html when completely offline and no cache exists.
 */
async function networkFirst(request) {
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached = await caches.match(request);
    if (cached) return cached;
    return caches.match('404.html');
  }
}

/**
 * Cache-first: serve from cache if available, otherwise fetch, cache,
 * and return. Silently ignores non-OK responses (e.g. 404).
 */
async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;

  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    return new Response('', { status: 503, statusText: 'Service Unavailable' });
  }
}
